### PR TITLE
Shp2json ext

### PR DESCRIPTION
**Pull request by bbuzz31**
Change `.shp` extension to `.json`.
See: https://github.com/aria-tools/ARIA-tools/pull/181

### CODE REVIEW

**Comment by EJFielding** [comment]
David was suggesting that someone also add the command for generating a true ESRI Shapefile `ogr2ogr -f "ESRI Shapefile" destination_data.shp "source-data.json" ` somewhere. I am not sure if it would be better at the end of the `JupyterDocs/ariaExtract/ariaExtract_tutorial.ipynb` you modified here or in the GDAL tutorial.

**Comment by EJFielding** [comment]
@dbekaert @sssangha I would suggest changing the util name to "plotpoly" or something like that. Polygons can be stored in either shapefile or geojson format.

**Comment by bbuzz31** [comment]
@dbekaert can you provide more detail on the masking error?

**Comment by bbuzz31** [comment]
@dbekaert the masking problems is fixed, and cell outputs have been cleaned and collapsed.
However, I recommend we also include a rendered version, that has everything unfolded and run, similar to https://github.com/ICESAT-2HackWeek/ICESat2_hackweek_tutorials/tree/master/06_Gridding_Nilsson/notebook. 

This would make it much easier for the user to use these notebooks as references.

**Comment by dbekaert** [comment]
@bbuzz31 also want to make sure that the repo remains in manageable size. Prior to integration can you pursue options that not all layers are downloaded each time?

**Comment by bbuzz31** [comment]
@dbekaert the rendered version is only a few KB larger than the un-rendered. In this case they're both just 1 MB.  You can take a look for yourself if you'd like, I just pushed one.

**Comment by dbekaert** [comment]
@bbuzz31 so would be at least a dupplication of the repo size.
What would be the difference of just uploading the notebooks directly with full cells included? 

The README page also give the Jypter notebook pre-view not in html; but it could be used for the actual notebooks with cell executed.

**Comment by dbekaert** [comment]
example: https://nbviewer.jupyter.org/github/aria-tools/ARIA-tools-docs/blob/master/JupyterDocs/ariaDownload/ariaDownload_tutorial.ipynb 

So if we would upload uncleaned cell the landing page could be used for reference. instead of duplicating html size of notebooks.

**Comment by bbuzz31** [comment]
Yes this seems to be the best option. I’ll go ahead and render them all.

**Comment by dbekaert** [comment]
> Yes this seems to be the best option. I’ll go ahead and render them all.
> […](#)

Can you also let me know the repo size before and after the rendering?

We should update the docs page to show how to only pull up to depth 1.
This would not force users to pull the complete history of the repository too.

**Comment by bbuzz31** [comment]
I've updated the repo to render all the notebooks. This increases the size only slightly, from 775 MB to 786 MB. 

However, this pull request doesn't seem to be getting updated with the latest commits (i.e. if you go to https://github.com/bbuzz31/ARIA-tools-docs you will see that they've been pushed there). I will wait to see if anyone has suggestions on how to fix this, or just issue a new pull request.

**Comment by dbekaert** [comment]
What do you mean, the PR does not seem to be updated?

Are you referring to the links on the README page?
Those point to the main repo and would only be updated once its merged.

**Comment by bbuzz31** [comment]
The last 3 commits I pushed weren't showing in this repo when I made them (and up to about 15 minutes after when I last checked). But they're here now, so we should be good to go.

**Comment by bbuzz31** [comment]
@bbuzz31 reminder to update readme to point links at new notebooks, following offline discussion

**Comment by dbekaert** [comment]
@bbuzz31 i understand you still had some items todo no? you might want to move it to drat status.

**Comment by bbuzz31** [comment]
@dbekaert thanks for reminding me; should be good to go now.

**Pull request merged**
