### PR TITLE
Update notebooks for glo30 dem

### PR DESCRIPTION
**Pull request by sssangha**

### CODE REVIEW

**Comment by bbuzz31** [comment]
Something seems wrong in the last cell of ariaTSsetup.py.

**Comment by bbuzz31** [comment]
Can we change the nodata to 0 in the waterMask plotting to be consistent with what is seen in MintPy (I often get confused by this)

**Comment by sssangha** [comment]
> 

Ok I ran through ariaTSsetup successfully and uploaded the notebook here.

Welcome to take a look at this, but not sure I have the bandwidth right now to dig into this.

**Comment by bbuzz31** [comment]
When I run this branch locally and whatever is installed on opensarlab (release I assume), my mask looks black and white as before. I'm confused as to why yours could be different. It must have something to do with the nan value... perhaps you are using an old mask?

**Review by bbuzz31 — APPROVED** [review]

**Pull request merged**
